[package]
name = "web_application"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
crate = "0.0.2"
log = "0.4.17"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
nostr-sdk = "0.20"
chrono = "0.4.24"